### ISSUE TITLE
Missing slashes in path while loading widgets

### ISSUE THREAD

**Issue by Tomino2112** [vudash/vudash#31]
Not sure if I am doing something wrong, but I have followed the quick install and tried to open default dashboard and got following:

```
npm run-script start

> my-vudash-dashboard@ start C:\_WWW\ipp-vudash
> vudash

Loading dashboards from C:\_WWW\ipp-vudash
Server running
Dashboards available:
simple-dashboard at http://ipushpull1:3300/default.dashboard
after
'C:_WWWipp-vudash
ode_modulesudash-widget-timesrcclientmarkup.html' is imported by dashboard.js, but could not be resolved – treating it as an external dependency
No name was provided for external module 'C:_WWWipp-vudash
ode_modulesudash-widget-timesrcclientmarkup.html' in options.globals – guessing 'VudashWidgetTime'
```

It seems that when loading widget markup all slashes disappear from the file path

**Comment by Tomino2112** [comment]
This seem to be windows only issue, on linux it works as expected

**Comment by antony** [comment]
Hi @Tomino2112 

Thanks for the report - I've actually never tried to run it on Windows, which is probably why it doesn't work! I can see that the backslashes are turning their adjacent characters into escape-chars.

I'll see if I can find out how to fix this - but I'll have to find a windows machine first!

For now you could run it on Linux / Run it inside docker as a workaround.

**Comment by Tomino2112** [comment]
Hi @antony  I am actually still debugging it and so far tracked it to the `rollup` package. I am not familiar with this module, maybe misconfiguration? You have a `configuration-builder` there that dynamically creates the rollup config, maybe would be as easy as change the generated config?

**Comment by antony** [comment]
Hmm - The rollup plugin responsible for composing the svelte components, which is what it looks like is failing on your system. Strange, as I'd expect rollup/rollup-plugin-svelte to work across all Operating Systems.

**Comment by Tomino2112** [comment]
Right, you could fix the issue from your side, I have just done it but definitely not pretty solution.

In `src/modules/dashboard/bundle-builder/index.js:25`

I have added:

```
for(var i = 0; i < imports.length; i++){
  imports[i] = imports[i].split("\\").join("/");
}
```

And that fixed the issue

**Comment by antony** [comment]
HI,

So it seems that the way I dynamically write the dashboard js bundle is writing import strings and escaping them which means that `\\` is being turned into `\`.

What I've done is I've made a fix in `7.6.2` which pre-converts windows paths to unix paths (which windows understands as you've demonstrated above), so this should work on all platforms.

Give `7.6.2` a go and see if you have any luck :)

**Comment by Tomino2112** [comment]
@antony Will do probably tomorrow, I found another issue do you want it here or in new git issue ?

**Comment by Tomino2112** [comment]
@antony  That's done it ! thanks
