### ISSUE TITLE
Rollup error on viewing dashboard

### ISSUE THREAD

**Issue by thomson02** [vudash/vudash#32]
I receive the following error message when I try to view a dashboard:

> TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at enhance (/[path]/vudash-example/node_modules/vudash/node_modules/rollup/dist/rollup.js:7567:21)
    at Module.analyse (/[path]/vudash-example/node_modules/vudash/node_modules/rollup/dist/rollup.js:7931:2)
    at new Module (/[path]/vudash-example/node_modules/vudash/node_modules/rollup/dist/rollup.js:7791:7)
    at /[path]/vudash-example/node_modules/vudash/node_modules/rollup/dist/rollup.js:9495:17

**Steps to reproduce:**
1. npm install -g vudash 
2. vudash create
3. npm start
4. browse to http://localhost:3300/default.dashboard
5. page does not load and the above error is displayed in the terminal.

I can also reproduce the issue when cloning the example repo: https://github.com/vudash/vudash-demo

**Versions:**
vudash: occurs from v7 -> v7.6.2
os: macOs Sierra v10.12.5
node: v6.10.1

**Comment by thomson02** [comment]
Issue also occurs when using Win10 and node v6.9.1

**Comment by antony** [comment]
Hi - you can't run Vudash on Node v6. It runs on 7.x and above. I think that is the root cause of your issues.

**Comment by antony** [comment]
Hey @thomson02 did this fix your problem?

**Comment by antony** [comment]
Closing - feel free to re-open if you have further issues.

**Comment by antony** [comment]
Hi @thomson02 looks like your problem is resolved the same way as in #33 

I hadn't realised that there was an issue with third party dependencies, so my apologies for that.

Vudash 7.6.3 will resolve your issue.
