### ISSUE TITLE
Error starting dashboard

### ISSUE THREAD

**Issue by mathiasschopmans** [vudash/vudash#33]
Hi everyone,
I just wanted to report, that I'm not able to get the basic setup running.

```
npm i -g vudash
vudash create
vudash

Loading dashboards from /Users/mathiasschopmans/Sites/om3-common/oms-dashboard
Server running
Dashboards available:
simple-dashboard at http://aoe-schopmans.local:3300/default.dashboard
```

Everything seems fine, but once I visit the logged URL I get the following error:

```
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at enhance (/Users/mathiasschopmans/Sites/oms-dashboard/node_modules/rollup/dist/rollup.js:7567:23)
    at Module.analyse (/Users/mathiasschopmans/Sites/oms-dashboard/node_modules/rollup/dist/rollup.js:7931:2)
    at new Module (/Users/mathiasschopmans/Sites/oms-dashboard/node_modules/rollup/dist/rollup.js:7791:7)
    at /Users/mathiasschopmans/Sites/oms-dashboard/node_modules/rollup/dist/rollup.js:9495:17
    at <anonymous>
```

**System information**

| Component | Version |
| --- | --- |
| OS | MacOS Sierra |
| node.js | 8.1.3 |
| npm | 5.0.4 |

**Comment by mathiasschopmans** [comment]
Related to #32

**Comment by antony** [comment]
Interesting, this immediately points to a node version error but it looks like you're using a recent version of node.

I'll see if I can replicate the error locally and get back to you.

**Comment by antony** [comment]
Ok - I've got the same error. I think perhaps there has been a minor release of a dependent package which has caused this. I'll have a look and see if I can fix it!

**Comment by mathiasschopmans** [comment]
I tried various node versions (6, 7, 8) and I think you're right with the dependent package causing this.

Thanks for investigating @antony!

**Comment by antony** [comment]
I've found the problem - some sort of incompatibility with the version of svelte and rollup.

Fixing those strangely revealed a problem with node v8 and 'cli'.

Pushing a new release shortly!

**Comment by alexanderyarm** [comment]
@antony works like a charm! thanks for fixing issue so quick!

**Comment by antony** [comment]
Super :D
