### ISSUE TITLE
Local modules can't be found

### ISSUE THREAD

**Issue by alexanderyarm** [vudash/vudash#38]
I have updated to the latest version `7.11.0` and have following error
`Module dependency widgets/vudash-chartjs declared in widget could not be located`
this is my local widget and it can't be found anymore.

I guess reason is this change https://github.com/vudash/vudash/commit/d617f8318f997d1434025e99193f2d08c105cbae#diff-573418c3c4b7a3f5236ad3e02d0b58d7L11

**Comment by antony** [comment]
Hi @alexanderyarm Yes - I saw this myself. I am working on a proper resolution, but for now, the node standard way of running the app with:

```NODE_PATH=. vudash``` will work.

Sorry about that!

**Comment by alexanderyarm** [comment]
yes, it works!

Thanks for quick response

**Comment by antony** [comment]
The way it was handled previously was suboptimal and overcomplicated, so I'm investigating a good way to do it. Suggestions welcome!

**Comment by antony** [comment]
I think I might have fixed this in v8 - I've rewritten a lot of stuff.

You might need to migrate your dashboard json and components, and datasources, though, I'll work on a migration guide to help.
