### ISSUE TITLE
datasource-rest crashes dashboard when 404/500/whatever occurs

### ISSUE THREAD

**Issue by alex-voigt** [vudash/vudash#50]
We just experienced the following issue when a URL is temporary not available:

```
ParseError: Unexpected token < in JSON at position 0 in "https://some.url.com/version.json":
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<c...
    at stream.catch.then.data (/Users/dashboard/node_modules/got/index.js:118:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
  message: 'Unexpected token < in JSON at position 0 in "https://some.url.com/version.json": \n<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor="white">\r\n<c...',
  host: 'some.url.com',
  hostname: 'some.url.com',
  method: 'GET',
  path: '/version.json',
  statusCode: 404,
  statusMessage: 'Not Found' }
node.js exiting due to unhandled promise rejection
```

Would be nice to make this failsafe to not crash the whole dashboard. It should rather get the values in the next fetching iteration (when the source is available again).

**Comment by antony** [comment]
Does this crash the entire dashboard? I believed it would just continue and retry - I have a few widgets which get this error a lot and simply carry on later.

Either way it is a bit messy. I'll see if I can shore up the error a bit and make it more stable.

**Comment by antony** [comment]
Ok, errors are handled and logged more gracefully now. They still don't show in the UI (only socket errors show here).

**Comment by antony** [comment]
v9.2.2 btw :)
