### ISSUE TITLE
Docs are not accessible

### ISSUE THREAD

**Issue by JanPokorny** [vudash/vudash#86]
http://vudash.github.io/vudash/ redirects to vudash.com, which is down.

**Comment by antony** [comment]
Same as https://github.com/vudash/vudash/issues/85

**Comment by JanPokorny** [comment]
@antony Why not just remove the redirect? Are the docs not able to run from gh-pages alone?

**Comment by antony** [comment]
Yeah they should be able to. A bit time constrained right now but I think I've done it?

**Comment by JanPokorny** [comment]
@antony Redirect seems to be gone now, thanks!
